version: "3.8"

services:
  api:
    container_name: api
    build: ./api
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      RCON_PASSWORD: ${RCON_PASSWORD}
    volumes:
      - ./api:/app
    depends_on:
      - minecraft

  minecraft:
    build: ./minecraft
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      MEMORYSIZE: "1G"
      PAPERMC_FLAGS: ""
      RCON_PASSWORD: ${RCON_PASSWORD}
    volumes:
      - ./minecraft/data:/data:rw
    restart: unless-stopped
volumes:
  minecraft:
